const express = require("express");
const {
  getEndpoints,
  endpointNotFound,
} = require("./controllers/endpoints.controller");
const { getTopics } = require("./controllers/topics.controller");
const {
  getArticle,
  getAllArticles,
  patchArticle,
} = require("./controllers/articles.controller");
const {
  getComments,
  postComment,
  deleteComment,
} = require("./controllers/comments.controller");
const { getUsers } = require("./controllers/users.controller");

const app = express();

app.use(express.json());

app.get("/api", getEndpoints);

app.get("/api/topics", getTopics);

app.get("/api/articles", getAllArticles);

app.get("/api/articles/:article_id", getArticle);
app.patch("/api/articles/:article_id", patchArticle);

app.get("/api/articles/:article_id/comments", getComments);
app.post("/api/articles/:article_id/comments", postComment);

app.delete("/api/comments/:comment_id", deleteComment);

app.get("/api/users", getUsers);

app.all("*", endpointNotFound);

app.use((err, req, res, next) => {
  const { msg, status } = err;
  if (msg && status) {
    res.status(status).send({ error: msg });
  } else {
    next(err);
  }
});

app.use((err, req, res, next) => {
  const { code } = err;
  if (code) {
    //property called 'code' is from error generated by sql
    res.status(400).send({ error: "Bad request" });
  } else {
    next(err);
  }
});

app.use((err, req, res, next) => {
  console.log("there is an error 500=======>\n", err);
  res.status(500).send({ error: "Internal server error" });
});

module.exports = app;
